# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.0
pipelines:
  #  default:
  #    - step:
  #        caches:
  #          - node
  #        script: # Modify the commands below to build your repository.
  #          - npm install
  #          - npm run build
  branches:
    master:
      - step:
          deployment: production
          caches:
            - node
          script:
            - npm install
            - npm run build
            - pipe: atlassian/rsync-deploy:0.3.2
              variables:
                USER: "nicu"
                SERVER: "185.104.181.210"
                REMOTE_PATH: "/var/www/demo-movies/"
                LOCAL_PATH: "dist/*"
                PASSWORD: $PASSWORD